services:
  mongodb:
    image: mongo:latest
    container_name: minecraft_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_data:/data/db
  redis:
    image: redis:alpine
    container_name: minecraft_redis
    ports:
      - 6379:6379
    command: redis-server --save 30 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: